### ISSUE TITLE
Button design/interaction consistency

### ISSUE THREAD

**Issue by maydeyn** [developerBME/street_care_webapp#5]
Noticed some inconsistencies for the buttons on homepage (different size, hover effects, etc)

Would it be possible to create a reusable component for the buttons? 
<img width="1018" alt="image" src="https://github.com/developerBME/street_care_webapp/assets/37945190/312fbf29-81f8-4897-b890-0c45c76f7372">

Figma link:
https://www.figma.com/file/4dlXoDdvLgU47zu6FEOZX2/%F0%9F%9F%A9-Street-Care?type=design&node-id=703%3A19341&mode=design&t=yuEm0bACZyrdM6oD-1

**Comment by logicb0mb** [comment]
@niravpatell23 once @shivanipandit88 is done with her form, she can start working on this.

@maydeyn feel free to make a few more issues for other reusable general components too.
